# Configuraciones del servidor
server:
  port: 9090
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Configuraciones de spring cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
        default-filters: TokenRelay
        routes:
          - id: ms-bill-route
            uri: lb://ms-bill
            predicates: Path=/bills/**
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/parcial-javier-paredes
        registration:
            keycloak-provider:
              client-id: gateway-client
              client-secret: 8CyMAAhr3OiAV2nGP8ieJ83Bn2PIcHMz
              scope:
                - openid
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
